### ISSUE TITLE
Drop `use_local: true` from CUDA 12 migrator

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/theseus-ai-feedstock#20]
Now that we are on PyTorch 2.4 ( https://github.com/conda-forge/theseus-ai-feedstock/pull/19 ), which [vendors pybind11 2.12.0]( https://github.com/pytorch/pytorch/commit/6c2f36c9845f310db8ece23c0d2e4ad6f702bc57 ), which in turn includes [the fix for this compiler error]( https://github.com/pybind/pybind11/commit/3414c56b6c7c521d868c9a137ca2ace2e26b5b2e ). Think we can drop this `use_local: true` line and clean this up

https://github.com/conda-forge/theseus-ai-feedstock/blob/ff7f26df3fbe5de1b090b0091bbac8feeb04bc82/.ci_support/migrations/cuda120.yaml#L5-L8

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin please rerender

**Comment by jakirkham** [comment]
Fixed in PR: https://github.com/conda-forge/theseus-ai-feedstock/pull/21
